#ifndef METADATA_FFI_H
#define METADATA_FFI_H

#pragma once

/* Generated by cbindgen — do not edit. Regenerate via the Gradle cbindgen task. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int id3_read_lyrics(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int id3_read_edited_lyrics(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int id3_read_album(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int id3_read_genre(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int id3_read_suno_clip_id(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int inf_read_extension(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

uint8_t *id3_read_cover(const uint8_t *input, uintptr_t in_len, uintptr_t *out_len);

uint8_t *id3_write_edited_lyrics(const uint8_t *input,
                                 uintptr_t in_len,
                                 const char *text,
                                 uintptr_t *out_len);

/**
 * Protagonist-picture write. Embeds `picture` (raw image bytes) as the APIC
 * LeadArtist frame, leaving cover/lyrics/other frames intact. Both `input` and
 * `picture` are borrowed `(ptr, len)` inputs; returns the new file bytes via the
 * owned-pointer shape (null on error, e.g. image-type inference failure).
 */
uint8_t *id3_write_protagonist(const uint8_t *input,
                               uintptr_t in_len,
                               const uint8_t *picture,
                               uintptr_t picture_len,
                               uintptr_t *out_len);

/**
 * SYLT edited-alignment write. `content` is a JSON string of `WordAlignment`
 * list: `[{"text":"...","start":0.123,"end":0.456}, ...]`. Returns new file
 * bytes via the owned-pointer shape (null on error).
 */
uint8_t *id3_write_edited_synced_lyrics(const uint8_t *input,
                                        uintptr_t in_len,
                                        const char *content,
                                        uintptr_t *out_len);

/**
 * Construct an engine and return its opaque handle. REAL (does not panic).
 */
int64_t aud_new(void);

/**
 * Drop the engine behind `handle` (no-op on a null handle).
 */
void aud_free(int64_t handle);

/**
 * Decode `bytes` into a sound slot; returns duration SECONDS.
 */
double aud_load(uint64_t handle, const uint8_t *input, uintptr_t in_len);

void aud_play(uint64_t handle, double from_sec);

void aud_pause(uint64_t handle);

void aud_resume(uint64_t handle);

void aud_seek_to(uint64_t handle, double sec);

void aud_seek_by(uint64_t handle, double sec);

void aud_set_loop(uint64_t handle, double a_sec, double b_sec);

void aud_clear_loop(uint64_t handle);

double aud_position(uint64_t handle);

uint8_t aud_state(uint64_t handle);

/**
 * Extract raw RGBA frames from `input_path` and write them to `output_path`.
 *
 * Panics on any error — there is no recovery path for video extraction.
 */
void cod_extract_rgba(const char *input_path, const char *output_path);

/**
 * Returns a JSON string of `List<WordAlignment>`: `[{"text":"...","start":0.123,"end":0.456}, ...]`.
 * `null` (return -1) when no edited SYLT frame exists.
 * Rust does all the SYLT parsing and word-boundary plumbing; Kotlin just deserializes.
 */
int id3_read_edited_synced_lyrics(const uint8_t *input,
                                  uintptr_t in_len,
                                  char *out,
                                  int out_cap);

/**
 * Decode a file at `path` into a sound slot; returns duration SECONDS.
 */
double aud_load_path(uint64_t handle, const char *path);

/**
 * Decodes input file to headerless little-endian interleaved f32 PCM, 16000 Hz
 * mono, written to `out_path`. Returns the PCM byte count; NEGATIVE means error.
 * Scaffold — real decode-to-PCM lands in M4.
 */
int64_t aud_decode_to_16k_mono_f32(const char *_input_path, const char *_out_path);

int xmp_read_original_document_id(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int xmp_read_genre(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int xmp_read_lyrics(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int xmp_read_rating(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

int xmp_read_project_name(const uint8_t *input, uintptr_t in_len, char *out, int out_cap);

#endif  /* METADATA_FFI_H */
