/*
 * matrix-service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "matrix_user_id")]
    pub matrix_user_id: String,
}

impl User {
    pub fn new(id: i32, matrix_user_id: String) -> User {
        User {
            id,
            matrix_user_id,
        }
    }
}

