CREATE TABLE IF NOT EXISTS care.prospects (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL UNIQUE,
    postcode VARCHAR(255) NULL,
    experience BOOLEAN NULL,
    personal_care BOOLEAN NOT NULL,
    hoisting BOOLEAN NOT NULL,
    stoma BOOLEAN NOT NULL,
    peg BOOLEAN NOT NULL,
    catheter BOOLEAN NOT NULL,
    support BOOLEAN NOT NULL,
    mon_morning BOOLEAN NOT NULL,
    mon_lunch BOOLEAN NOT NULL,
    mon_tea BOOLEAN NOT NULL,
    mon_evening BOOLEAN NOT NULL,
    mon_night BOOLEAN NOT NULL,
    tue_morning BOOLEAN NOT NULL,
    tue_lunch BOOLEAN NOT NULL,
    tue_tea BOOLEAN NOT NULL,
    tue_evening BOOLEAN NOT NULL,
    tue_night BOOLEAN NOT NULL,
    wed_morning BOOLEAN NOT NULL,
    wed_lunch BOOLEAN NOT NULL,
    wed_tea BOOLEAN NOT NULL,
    wed_evening BOOLEAN NOT NULL,
    wed_night BOOLEAN NOT NULL,
    thu_morning BOOLEAN NOT NULL,
    thu_lunch BOOLEAN NOT NULL,
    thu_tea BOOLEAN NOT NULL,
    thu_evening BOOLEAN NOT NULL,
    thu_night BOOLEAN NOT NULL,
    fri_morning BOOLEAN NOT NULL,
    fri_lunch BOOLEAN NOT NULL,
    fri_tea BOOLEAN NOT NULL,
    fri_evening BOOLEAN NOT NULL,
    fri_night BOOLEAN NOT NULL,
    sat_morning BOOLEAN NOT NULL,
    sat_lunch BOOLEAN NOT NULL,
    sat_tea BOOLEAN NOT NULL,
    sat_evening BOOLEAN NOT NULL,
    sat_night BOOLEAN NOT NULL,
    sun_morning BOOLEAN NOT NULL,
    sun_lunch BOOLEAN NOT NULL,
    sun_tea BOOLEAN NOT NULL,
    sun_evening BOOLEAN NOT NULL,
    sun_night BOOLEAN NOT NULL,
    note VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES care.users (id)
);
