database = "/Users/u/dbapps/femi/care.db"
osm = "/Users/u/dbapps/femi/london-surrey.osm.pbf"
gtfs = [
    "/Users/u/dbapps/femi/itm_london_gtfs.zip",
    "/Users/u/dbapps/femi/itm_south_east_gtfs.zip",
]
