//! The event-log spine — the harness's authoritative record.
//!
//! Ported from the proven Swift reference harness. Load-bearing properties:
//!   * the append-only event log IS the source of truth — conversation state is a
//!     `fold` over the log (`fold_transcript`), never a parallel mutable array;
//!     resume = replay.
//!   * typed content blocks instead of a flat string; media is **reference-not-bytes**
//!     (an item id + metadata, never base64) so generated bytes never pollute context.
//!   * opaque provider metadata (`provider_raw`) round-tripped byte-exact so the next
//!     request can echo the model's exact assistant message.
//!   * the transcript-validity invariant: exactly one tool_result per tool_use, in
//!     order, no orphans — checked before every model call.

use serde::{Deserialize, Serialize};

/// How a fault is classified. Lives here (not in `agent`) because `EventKind`
/// carries it on `ModelRetry` / `RunFailed`, and the log must be `Serialize`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FaultClass {
    ModelUnavailable, // connection refused / timeout / 5xx — RETRYABLE
    ModelProtocol,    // malformed / unparseable model output — terminal
    ToolTransient,    // a tool failure worth retrying
    ToolPermanent,    // a tool failure that will always fail
    TranscriptInvalid,
    Budget,
    Cancelled,
    Internal,
}

impl FaultClass {
    /// Only these engage the bounded-retry loop; everything else finalizes at once.
    pub fn is_retryable(self) -> bool {
        matches!(self, FaultClass::ModelUnavailable | FaultClass::ToolTransient)
    }
}

/// A typed content block. `ItemRef` is the reference-not-bytes media block.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "block", rename_all = "snake_case")]
pub enum ContentBlock {
    Text { text: String },
    ToolUse { id: String, name: String, args: String },
    ToolResult { id: String, summary: String, is_error: bool },
    ItemRef { item_id: String, kind: String, mime: String },
}

/// A transcript message: role + typed blocks + opaque provider metadata.
#[derive(Clone, Debug, PartialEq)]
pub struct Msg {
    pub role: String, // system | user | assistant | tool
    pub blocks: Vec<ContentBlock>,
    pub provider_raw: Option<String>, // provider's exact assistant-message JSON
    pub tool_call_id: Option<String>, // for role == "tool"
}

impl Msg {
    pub fn new(role: &str, blocks: Vec<ContentBlock>) -> Self {
        Msg { role: role.to_string(), blocks, provider_raw: None, tool_call_id: None }
    }
    pub fn text(role: &str, t: &str) -> Self {
        Msg::new(role, vec![ContentBlock::Text { text: t.to_string() }])
    }
}

/// The durable event. `seq` is assigned by the single log writer.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    pub seq: usize,
    pub run_id: String,
    pub turn: Option<u32>,
    pub kind: EventKind,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum EventKind {
    RunStarted { system: String, user: String },
    TurnStarted { turn: u32 },
    ModelRequest { turn: u32, msgs: usize },
    ModelRetry { turn: u32, fault: FaultClass, attempt: u32 },
    AssistantMessage { turn: u32, blocks: Vec<ContentBlock>, provider_raw: Option<String> },
    ItemProduced { item_id: String, kind: String, mime: String }, // reference only
    ToolResult { turn: u32, id: String, summary: String, is_error: bool },
    RunCompleted { turns: u32 },
    RunFailed { fault: FaultClass, reason: String },
    RunCancelled,
    BudgetExhausted { axis: String },
    Compaction { replaces_up_to_seq: usize, summary: String },
}

impl EventKind {
    /// A run ends on exactly one of these; the loop returns after appending it.
    pub fn is_terminal(&self) -> bool {
        matches!(
            self,
            EventKind::RunCompleted { .. }
                | EventKind::RunFailed { .. }
                | EventKind::RunCancelled
                | EventKind::BudgetExhausted { .. }
        )
    }
}

/// The append-only log. Single writer (the loop). State = fold over `events`.
///
/// An optional `on_append` sink is invoked synchronously after each event is
/// committed, in seq order — a lossless live view for a UI/stream, never a
/// mutation path.
pub struct EventLog {
    pub run_id: String,
    events: Vec<Event>,
    on_append: Option<Box<dyn Fn(&Event) + Send + Sync>>,
}

impl EventLog {
    pub fn new(run_id: impl Into<String>) -> Self {
        EventLog { run_id: run_id.into(), events: Vec::new(), on_append: None }
    }

    pub fn with_sink(run_id: impl Into<String>, sink: Box<dyn Fn(&Event) + Send + Sync>) -> Self {
        EventLog { run_id: run_id.into(), events: Vec::new(), on_append: Some(sink) }
    }

    pub fn events(&self) -> &[Event] {
        &self.events
    }

    pub fn append(&mut self, kind: EventKind, turn: Option<u32>) {
        let e = Event { seq: self.events.len(), run_id: self.run_id.clone(), turn, kind };
        self.events.push(e);
        if let Some(cb) = &self.on_append {
            cb(self.events.last().unwrap());
        }
    }
}

/// The transcript is a pure function of the log (state = fold, resume = replay).
///
/// Compaction-aware: the system prompt is a durable head (never compacted). The
/// last compaction event (if any) replaces every event with `seq < replaces_up_to_seq`
/// by its summary; events at/after that seq fold verbatim (the rolling window).
pub fn fold_transcript(log: &EventLog) -> Vec<Msg> {
    let mut system = String::new();
    if let Some(Event { kind: EventKind::RunStarted { system: s, .. }, .. }) = log.events().first() {
        system = s.clone();
    }

    let mut replaces_up_to = 0usize;
    let mut summary: Option<String> = None;
    for e in log.events() {
        if let EventKind::Compaction { replaces_up_to_seq, summary: s } = &e.kind {
            replaces_up_to = *replaces_up_to_seq;
            summary = Some(s.clone());
        }
    }

    let mut msgs = vec![Msg::text("system", &system)];
    if let Some(s) = &summary {
        msgs.push(Msg::text("user", &format!("[Summary of earlier conversation]\n{s}")));
    }

    for e in log.events() {
        if e.seq < replaces_up_to {
            continue; // represented by the summary
        }
        match &e.kind {
            EventKind::RunStarted { user, .. } => {
                if replaces_up_to == 0 {
                    msgs.push(Msg::text("user", user));
                }
            }
            EventKind::AssistantMessage { blocks, provider_raw, .. } => {
                let mut m = Msg::new("assistant", blocks.clone());
                m.provider_raw = provider_raw.clone();
                msgs.push(m);
            }
            EventKind::ToolResult { id, summary, is_error, .. } => {
                let mut m = Msg::new(
                    "tool",
                    vec![ContentBlock::ToolResult {
                        id: id.clone(),
                        summary: summary.clone(),
                        is_error: *is_error,
                    }],
                );
                m.tool_call_id = Some(id.clone());
                msgs.push(m);
            }
            _ => {} // bookkeeping / terminal / compaction don't project into the transcript
        }
    }
    msgs
}

#[derive(Debug, PartialEq, Eq)]
pub enum TranscriptError {
    OrphanToolResult(String),
    DuplicateToolResult(String),
    UnansweredToolUse(String),
}

/// Every tool_use is answered exactly once, before the transcript is complete;
/// no orphan or duplicate results. Checked before each model call.
pub fn validate_transcript(msgs: &[Msg]) -> Result<(), TranscriptError> {
    use std::collections::HashSet;
    let mut seen_use: HashSet<&str> = HashSet::new();
    let mut answered: HashSet<&str> = HashSet::new();
    let mut pending: Vec<&str> = Vec::new();

    for m in msgs {
        for b in &m.blocks {
            match b {
                ContentBlock::ToolUse { id, .. } => {
                    seen_use.insert(id);
                    pending.push(id);
                }
                ContentBlock::ToolResult { id, .. } => {
                    if answered.contains(id.as_str()) {
                        return Err(TranscriptError::DuplicateToolResult(id.clone()));
                    }
                    if !seen_use.contains(id.as_str()) {
                        return Err(TranscriptError::OrphanToolResult(id.clone()));
                    }
                    answered.insert(id);
                    pending.retain(|p| *p != id.as_str());
                }
                _ => {}
            }
        }
    }
    if let Some(first) = pending.first() {
        return Err(TranscriptError::UnansweredToolUse((*first).to_string()));
    }
    Ok(())
}
