[package]
name = "meta-service"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
xmp_toolkit = "1"
id3 = { workspace = true }
infer = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tower = { workspace = true }
