/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "DEPART")]
    Depart,
    #[serde(rename = "HARD_LEFT")]
    HardLeft,
    #[serde(rename = "LEFT")]
    Left,
    #[serde(rename = "SLIGHTLY_LEFT")]
    SlightlyLeft,
    #[serde(rename = "CONTINUE")]
    Continue,
    #[serde(rename = "SLIGHTLY_RIGHT")]
    SlightlyRight,
    #[serde(rename = "RIGHT")]
    Right,
    #[serde(rename = "HARD_RIGHT")]
    HardRight,
    #[serde(rename = "CIRCLE_CLOCKWISE")]
    CircleClockwise,
    #[serde(rename = "CIRCLE_COUNTERCLOCKWISE")]
    CircleCounterclockwise,
    #[serde(rename = "STAIRS")]
    Stairs,
    #[serde(rename = "ELEVATOR")]
    Elevator,
    #[serde(rename = "UTURN_LEFT")]
    UturnLeft,
    #[serde(rename = "UTURN_RIGHT")]
    UturnRight,

}

impl std::fmt::Display for Direction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Depart => write!(f, "DEPART"),
            Self::HardLeft => write!(f, "HARD_LEFT"),
            Self::Left => write!(f, "LEFT"),
            Self::SlightlyLeft => write!(f, "SLIGHTLY_LEFT"),
            Self::Continue => write!(f, "CONTINUE"),
            Self::SlightlyRight => write!(f, "SLIGHTLY_RIGHT"),
            Self::Right => write!(f, "RIGHT"),
            Self::HardRight => write!(f, "HARD_RIGHT"),
            Self::CircleClockwise => write!(f, "CIRCLE_CLOCKWISE"),
            Self::CircleCounterclockwise => write!(f, "CIRCLE_COUNTERCLOCKWISE"),
            Self::Stairs => write!(f, "STAIRS"),
            Self::Elevator => write!(f, "ELEVATOR"),
            Self::UturnLeft => write!(f, "UTURN_LEFT"),
            Self::UturnRight => write!(f, "UTURN_RIGHT"),
        }
    }
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Depart
    }
}

