/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LegId {
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "tripId")]
    pub trip_id: String,
    /// from stop stopId
    #[serde(rename = "fromId")]
    pub from_id: String,
    /// latitude of the leg's from endpoint
    #[serde(rename = "fromLat")]
    pub from_lat: f64,
    /// longitude of the leg's from endpoint
    #[serde(rename = "fromLon")]
    pub from_lon: f64,
    /// Optional level (floor) of the leg's from endpoint for indoor routing.
    #[serde(rename = "fromLevel", skip_serializing_if = "Option::is_none")]
    pub from_level: Option<f64>,
    /// to stop stopId
    #[serde(rename = "toId")]
    pub to_id: String,
    /// latitude of the leg's to endpoint
    #[serde(rename = "toLat")]
    pub to_lat: f64,
    /// longitude of the leg's to endpoint
    #[serde(rename = "toLon")]
    pub to_lon: f64,
    /// Optional level (floor) of the leg's to endpoint for indoor routing.
    #[serde(rename = "toLevel", skip_serializing_if = "Option::is_none")]
    pub to_level: Option<f64>,
    /// Scheduled departure time as a Unix timestamp in seconds.
    #[serde(rename = "schedStart")]
    pub sched_start: i64,
    /// Scheduled arrival time as a Unix timestamp in seconds.
    #[serde(rename = "schedEnd")]
    pub sched_end: i64,
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    #[serde(rename = "scheduled")]
    pub scheduled: bool,
}

impl LegId {
    pub fn new(display_name: String, trip_id: String, from_id: String, from_lat: f64, from_lon: f64, to_id: String, to_lat: f64, to_lon: f64, sched_start: i64, sched_end: i64, mode: models::Mode, scheduled: bool) -> LegId {
        LegId {
            display_name,
            trip_id,
            from_id,
            from_lat,
            from_lon,
            from_level: None,
            to_id,
            to_lat,
            to_lon,
            to_level: None,
            sched_start,
            sched_end,
            mode,
            scheduled,
        }
    }
}

