/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OneToManyIntermodalParams {
    /// \\`latitude,longitude[,level]\\` tuple with - latitude and longitude in degrees - (optional) level: the OSM level (default: 0)  OR  stop id 
    #[serde(rename = "one")]
    pub one: String,
    /// array of:  \\`latitude,longitude[,level]\\` tuple with - latitude and longitude in degrees - (optional) level: the OSM level (default: 0)  OR  stop id  The number of accepted locations is limited by server config variable `onetomany_max_many`. 
    #[serde(rename = "many")]
    pub many: Vec<String>,
    /// Optional. Defaults to the current time.  Departure time ($arriveBy=false) / arrival date ($arriveBy=true), 
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The maximum travel time in minutes. If not provided, the routing uses the value hardcoded in the server which is usually quite high.  *Warning*: Use with care. Setting this too low can lead to optimal (e.g. the least transfers) journeys not being found. If this value is too low to reach the destination at all, it can lead to slow routing performance. 
    #[serde(rename = "maxTravelTime", skip_serializing_if = "Option::is_none")]
    pub max_travel_time: Option<i32>,
    /// maximum matching distance in meters to match geo coordinates to the street network  Is limited by server config variable `max_max_matching_distance`, larger values are capped to this limit. 
    #[serde(rename = "maxMatchingDistance", skip_serializing_if = "Option::is_none")]
    pub max_matching_distance: Option<f64>,
    /// Optional. Defaults to false, i.e. one to many search  true = many to one false = one to many 
    #[serde(rename = "arriveBy", skip_serializing_if = "Option::is_none")]
    pub arrive_by: Option<bool>,
    /// The maximum number of allowed transfers (i.e. interchanges between transit legs, pre- and postTransit do not count as transfers). `maxTransfers=0` searches for direct transit connections without any transfers. If you want to search only for non-transit connections (`FOOT`, `CAR`, etc.), send an empty `transitModes` parameter instead.  If not provided, the routing uses the server-side default value which is hardcoded and very high to cover all use cases.  *Warning*: Use with care. Setting this too low can lead to optimal (e.g. the fastest) journeys not being found. If this value is too low to reach the destination at all, it can lead to slow routing performance. 
    #[serde(rename = "maxTransfers", skip_serializing_if = "Option::is_none")]
    pub max_transfers: Option<i32>,
    /// Optional. Default is 0 minutes.  Minimum transfer time for each transfer in minutes. 
    #[serde(rename = "minTransferTime", skip_serializing_if = "Option::is_none")]
    pub min_transfer_time: Option<i32>,
    /// Optional. Default is 0 minutes.  Additional transfer time reserved for each transfer in minutes. 
    #[serde(rename = "additionalTransferTime", skip_serializing_if = "Option::is_none")]
    pub additional_transfer_time: Option<i32>,
    /// Optional. Default is 1.0  Factor to multiply minimum required transfer times with. Values smaller than 1.0 are not supported. 
    #[serde(rename = "transferTimeFactor", skip_serializing_if = "Option::is_none")]
    pub transfer_time_factor: Option<f64>,
    /// Optional. Default is `false`.  Whether to use transfers routed on OpenStreetMap data. 
    #[serde(rename = "useRoutedTransfers", skip_serializing_if = "Option::is_none")]
    pub use_routed_transfers: Option<bool>,
    /// Optional. Default is `FOOT`.  Accessibility profile to use for pedestrian routing in transfers between transit connections and the first and last mile respectively. 
    #[serde(rename = "pedestrianProfile", skip_serializing_if = "Option::is_none")]
    pub pedestrian_profile: Option<models::PedestrianProfile>,
    /// Optional  Average speed for pedestrian routing. 
    #[serde(rename = "pedestrianSpeed", skip_serializing_if = "Option::is_none")]
    pub pedestrian_speed: Option<f64>,
    /// Optional  Average speed for bike routing. 
    #[serde(rename = "cyclingSpeed", skip_serializing_if = "Option::is_none")]
    pub cycling_speed: Option<f64>,
    /// Vehicle height for HGV routing in meters
    #[serde(rename = "vehicleHeight", skip_serializing_if = "Option::is_none")]
    pub vehicle_height: Option<f64>,
    /// Vehicle width for HGV routing in meters
    #[serde(rename = "vehicleWidth", skip_serializing_if = "Option::is_none")]
    pub vehicle_width: Option<f64>,
    /// Vehicle length for HGV routing in meters
    #[serde(rename = "vehicleLength", skip_serializing_if = "Option::is_none")]
    pub vehicle_length: Option<f64>,
    /// Vehicle gross weight for HGV routing in tons
    #[serde(rename = "vehicleWeight", skip_serializing_if = "Option::is_none")]
    pub vehicle_weight: Option<f64>,
    /// Whether the vehicle carries hazardous materials for HGV routing
    #[serde(rename = "vehicleHazmat", skip_serializing_if = "Option::is_none")]
    pub vehicle_hazmat: Option<bool>,
    /// Whether the vehicle carries hazardous materials dangerous to water for HGV routing
    #[serde(rename = "vehicleHazmatWater", skip_serializing_if = "Option::is_none")]
    pub vehicle_hazmat_water: Option<bool>,
    /// Axle count for HGV routing
    #[serde(rename = "vehicleAxleCount", skip_serializing_if = "Option::is_none")]
    pub vehicle_axle_count: Option<i32>,
    /// Maximum axle load for HGV routing in tons
    #[serde(rename = "vehicleAxleLoad", skip_serializing_if = "Option::is_none")]
    pub vehicle_axle_load: Option<f64>,
    /// Whether the vehicle has a trailer for HGV routing
    #[serde(rename = "vehicleTrailer", skip_serializing_if = "Option::is_none")]
    pub vehicle_trailer: Option<bool>,
    /// Vehicle top speed for HGV routing in km/h
    #[serde(rename = "vehicleTopSpeed", skip_serializing_if = "Option::is_none")]
    pub vehicle_top_speed: Option<i32>,
    /// Whether the vehicle is allowed to use low-emission zones for HGV routing
    #[serde(rename = "vehicleLezAccess", skip_serializing_if = "Option::is_none")]
    pub vehicle_lez_access: Option<bool>,
    /// Optional. Default is `NONE`.  Set an elevation cost profile, to penalize routes with incline. - `NONE`: No additional costs for elevations. This is the default behavior - `LOW`: Add a low cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if small detours are required. - `HIGH`: Add a high cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if larger detours are required.  As using an elevation costs profile will increase the travel duration, routing through steep terrain may exceed the maximal allowed duration, causing a location to appear unreachable. Increasing the maximum travel time for these segments may resolve this issue.  The profile is used for routing on both the first and last mile.  Elevation cost profiles are currently used by following street modes: - `BIKE` 
    #[serde(rename = "elevationCosts", skip_serializing_if = "Option::is_none")]
    pub elevation_costs: Option<models::ElevationCosts>,
    /// Optional. Default is `TRANSIT` which allows all transit modes (no restriction). Allowed modes for the transit part. If empty, no transit connections will be computed. For example, this can be used to allow only `SUBURBAN,SUBWAY,TRAM`. 
    #[serde(rename = "transitModes", skip_serializing_if = "Option::is_none")]
    pub transit_modes: Option<Vec<models::Mode>>,
    /// Optional. Default is `WALK`. Does not apply to direct connections (see `directMode`).  A list of modes that are allowed to be used for the first mile, i.e. from the coordinates to the first transit stop. Example: `WALK,BIKE_SHARING`. 
    #[serde(rename = "preTransitModes", skip_serializing_if = "Option::is_none")]
    pub pre_transit_modes: Option<Vec<models::Mode>>,
    /// Optional. Default is `WALK`. Does not apply to direct connections (see `directMode`).  A list of modes that are allowed to be used for the last mile, i.e. from the last transit stop to the target coordinates. Example: `WALK,BIKE_SHARING`. 
    #[serde(rename = "postTransitModes", skip_serializing_if = "Option::is_none")]
    pub post_transit_modes: Option<Vec<models::Mode>>,
    /// Default is `WALK` which will compute walking routes as direct connections.  Mode used for direction connections from start to destination without using transit.  Currently supported non-transit modes: \\`WALK\\`, \\`BIKE\\`, \\`CAR\\` 
    #[serde(rename = "directMode", skip_serializing_if = "Option::is_none")]
    pub direct_mode: Option<models::Mode>,
    /// Optional. Default is 15min which is `900`. Maximum time in seconds for the first street leg. Is limited by server config variable `street_routing_max_prepost_transit_seconds`. 
    #[serde(rename = "maxPreTransitTime", skip_serializing_if = "Option::is_none")]
    pub max_pre_transit_time: Option<i32>,
    /// Optional. Default is 15min which is `900`. Maximum time in seconds for the last street leg. Is limited by server config variable `street_routing_max_prepost_transit_seconds`. 
    #[serde(rename = "maxPostTransitTime", skip_serializing_if = "Option::is_none")]
    pub max_post_transit_time: Option<i32>,
    /// Optional. Default is 30min which is `1800`. Maximum time in seconds for direct connections.  If a value smaller than either `maxPreTransitTime` or `maxPostTransitTime` is used, their maximum is set instead. Is limited by server config variable `street_routing_max_direct_seconds`. 
    #[serde(rename = "maxDirectTime", skip_serializing_if = "Option::is_none")]
    pub max_direct_time: Option<i32>,
    /// If true, the response includes the distance in meters for each path. This requires path reconstruction and may be slower than duration-only queries.  `withDistance` is currently limited to street routing. 
    #[serde(rename = "withDistance", skip_serializing_if = "Option::is_none")]
    pub with_distance: Option<bool>,
    /// Optional. Default is `false`.  If set to `true`, all used transit trips are required to allow bike carriage. 
    #[serde(rename = "requireBikeTransport", skip_serializing_if = "Option::is_none")]
    pub require_bike_transport: Option<bool>,
    /// Optional. Default is `false`.  If set to `true`, all used transit trips are required to allow car carriage. 
    #[serde(rename = "requireCarTransport", skip_serializing_if = "Option::is_none")]
    pub require_car_transport: Option<bool>,
    /// Optional. Default is `false`.  If set to `true`, all used transit trips are required to be usable without compulsory reservation. 
    #[serde(rename = "noCompulsoryReservation", skip_serializing_if = "Option::is_none")]
    pub no_compulsory_reservation: Option<bool>,
}

impl OneToManyIntermodalParams {
    pub fn new(one: String, many: Vec<String>) -> OneToManyIntermodalParams {
        OneToManyIntermodalParams {
            one,
            many,
            time: None,
            max_travel_time: None,
            max_matching_distance: None,
            arrive_by: None,
            max_transfers: None,
            min_transfer_time: None,
            additional_transfer_time: None,
            transfer_time_factor: None,
            use_routed_transfers: None,
            pedestrian_profile: None,
            pedestrian_speed: None,
            cycling_speed: None,
            vehicle_height: None,
            vehicle_width: None,
            vehicle_length: None,
            vehicle_weight: None,
            vehicle_hazmat: None,
            vehicle_hazmat_water: None,
            vehicle_axle_count: None,
            vehicle_axle_load: None,
            vehicle_trailer: None,
            vehicle_top_speed: None,
            vehicle_lez_access: None,
            elevation_costs: None,
            transit_modes: None,
            pre_transit_modes: None,
            post_transit_modes: None,
            direct_mode: None,
            max_pre_transit_time: None,
            max_post_transit_time: None,
            max_direct_time: None,
            with_distance: None,
            require_bike_transport: None,
            require_car_transport: None,
            no_compulsory_reservation: None,
        }
    }
}

