/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OneToManyParams {
    /// geo location as latitude;longitude
    #[serde(rename = "one")]
    pub one: String,
    /// geo locations as latitude;longitude,latitude;longitude,...  The number of accepted locations is limited by server config variable `onetomany_max_many`. 
    #[serde(rename = "many")]
    pub many: Vec<String>,
    /// routing profile to use (currently supported: \\`WALK\\`, \\`BIKE\\`, \\`CAR\\`) 
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    /// maximum travel time in seconds. Is limited by server config variable `street_routing_max_direct_seconds`.
    #[serde(rename = "max")]
    pub max: f64,
    /// maximum matching distance in meters to match geo coordinates to the street network  Is limited by server config variable `max_max_matching_distance`, larger values are capped to this limit. 
    #[serde(rename = "maxMatchingDistance")]
    pub max_matching_distance: f64,
    /// Optional. Default is `NONE`.  Set an elevation cost profile, to penalize routes with incline. - `NONE`: No additional costs for elevations. This is the default behavior - `LOW`: Add a low cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if small detours are required. - `HIGH`: Add a high cost for increase in elevation and incline along the way. This will prefer routes with less ascent, if larger detours are required.  As using an elevation costs profile will increase the travel duration, routing through steep terrain may exceed the maximal allowed duration, causing a location to appear unreachable. Increasing the maximum travel time for these segments may resolve this issue.  Elevation cost profiles are currently used by following street modes: - `BIKE` 
    #[serde(rename = "elevationCosts", skip_serializing_if = "Option::is_none")]
    pub elevation_costs: Option<models::ElevationCosts>,
    /// true = many to one false = one to many 
    #[serde(rename = "arriveBy")]
    pub arrive_by: bool,
    /// If true, the response includes the distance in meters for each path. This requires path reconstruction and may be slower than duration-only queries. 
    #[serde(rename = "withDistance", skip_serializing_if = "Option::is_none")]
    pub with_distance: Option<bool>,
}

impl OneToManyParams {
    pub fn new(one: String, many: Vec<String>, mode: models::Mode, max: f64, max_matching_distance: f64, arrive_by: bool) -> OneToManyParams {
        OneToManyParams {
            one,
            many,
            mode,
            max,
            max_matching_distance,
            elevation_costs: None,
            arrive_by,
            with_distance: None,
        }
    }
}

