/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RealtimeMode : Controls whether realtime data (delays, cancellations, added/changed trips) is used.  - `REALTIME`: use realtime data for routing/sorting. - `REALTIME_ANNOTATION_ONLY`: route, sort and window on the scheduled   timetable only, but still annotate the response with realtime data. - `OFF`: use the scheduled timetable only, with no realtime annotation. 
/// Controls whether realtime data (delays, cancellations, added/changed trips) is used.  - `REALTIME`: use realtime data for routing/sorting. - `REALTIME_ANNOTATION_ONLY`: route, sort and window on the scheduled   timetable only, but still annotate the response with realtime data. - `OFF`: use the scheduled timetable only, with no realtime annotation. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RealtimeMode {
    #[serde(rename = "false")]
    False,
    #[serde(rename = "REALTIME_ANNOTATION_ONLY")]
    RealtimeAnnotationOnly,
    #[serde(rename = "REALTIME")]
    Realtime,

}

impl std::fmt::Display for RealtimeMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::False => write!(f, "false"),
            Self::RealtimeAnnotationOnly => write!(f, "REALTIME_ANNOTATION_ONLY"),
            Self::Realtime => write!(f, "REALTIME"),
        }
    }
}

impl Default for RealtimeMode {
    fn default() -> RealtimeMode {
        Self::False
    }
}

