/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RentalFormFactor {
    #[serde(rename = "BICYCLE")]
    Bicycle,
    #[serde(rename = "CARGO_BICYCLE")]
    CargoBicycle,
    #[serde(rename = "CAR")]
    Car,
    #[serde(rename = "MOPED")]
    Moped,
    #[serde(rename = "SCOOTER_STANDING")]
    ScooterStanding,
    #[serde(rename = "SCOOTER_SEATED")]
    ScooterSeated,
    #[serde(rename = "OTHER")]
    Other,

}

impl std::fmt::Display for RentalFormFactor {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bicycle => write!(f, "BICYCLE"),
            Self::CargoBicycle => write!(f, "CARGO_BICYCLE"),
            Self::Car => write!(f, "CAR"),
            Self::Moped => write!(f, "MOPED"),
            Self::ScooterStanding => write!(f, "SCOOTER_STANDING"),
            Self::ScooterSeated => write!(f, "SCOOTER_SEATED"),
            Self::Other => write!(f, "OTHER"),
        }
    }
}

impl Default for RentalFormFactor {
    fn default() -> RentalFormFactor {
        Self::Bicycle
    }
}

