/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Routes200Response {
    #[serde(rename = "routes")]
    pub routes: Vec<models::RouteInfo>,
    #[serde(rename = "polylines")]
    pub polylines: Vec<models::RoutePolyline>,
    #[serde(rename = "stops")]
    pub stops: Vec<models::Place>,
    /// Indicates whether some routes were filtered out due to the zoom level. 
    #[serde(rename = "zoomFiltered")]
    pub zoom_filtered: bool,
}

impl Routes200Response {
    pub fn new(routes: Vec<models::RouteInfo>, polylines: Vec<models::RoutePolyline>, stops: Vec<models::Place>, zoom_filtered: bool) -> Routes200Response {
        Routes200Response {
            routes,
            polylines,
            stops,
            zoom_filtered,
        }
    }
}

