/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RouteInfo {
    /// Transport mode for this route
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    #[serde(rename = "transitRoutes")]
    pub transit_routes: Vec<models::TransitRouteInfo>,
    /// Number of stops along this route
    #[serde(rename = "numStops")]
    pub num_stops: i32,
    /// Internal route index for debugging purposes
    #[serde(rename = "routeIdx")]
    pub route_idx: i32,
    #[serde(rename = "pathSource")]
    pub path_source: models::RoutePathSource,
    #[serde(rename = "segments")]
    pub segments: Vec<models::RouteSegment>,
}

impl RouteInfo {
    pub fn new(mode: models::Mode, transit_routes: Vec<models::TransitRouteInfo>, num_stops: i32, route_idx: i32, path_source: models::RoutePathSource, segments: Vec<models::RouteSegment>) -> RouteInfo {
        RouteInfo {
            mode,
            transit_routes,
            num_stops,
            route_idx,
            path_source,
            segments,
        }
    }
}

