/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Route : a transit route/line serving a stop
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Route {
    #[serde(rename = "routeId")]
    pub route_id: String,
    #[serde(rename = "routeShortName")]
    pub route_short_name: String,
    #[serde(rename = "routeLongName")]
    pub route_long_name: String,
    #[serde(rename = "mode")]
    pub mode: models::Mode,
    #[serde(rename = "agencyId")]
    pub agency_id: String,
    #[serde(rename = "agencyName")]
    pub agency_name: String,
    #[serde(rename = "agencyUrl")]
    pub agency_url: String,
    #[serde(rename = "routeColor", skip_serializing_if = "Option::is_none")]
    pub route_color: Option<String>,
    #[serde(rename = "routeTextColor", skip_serializing_if = "Option::is_none")]
    pub route_text_color: Option<String>,
    #[serde(rename = "routeType", skip_serializing_if = "Option::is_none")]
    pub route_type: Option<i32>,
}

impl Route {
    /// a transit route/line serving a stop
    pub fn new(route_id: String, route_short_name: String, route_long_name: String, mode: models::Mode, agency_id: String, agency_name: String, agency_url: String) -> Route {
        Route {
            route_id,
            route_short_name,
            route_long_name,
            mode,
            agency_id,
            agency_name,
            agency_url,
            route_color: None,
            route_text_color: None,
            route_type: None,
        }
    }
}

