/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerConfig {
    /// the version of this MOTIS server
    #[serde(rename = "motisVersion")]
    pub motis_version: String,
    /// true if elevation is loaded
    #[serde(rename = "hasElevation")]
    pub has_elevation: bool,
    /// true if routed transfers available
    #[serde(rename = "hasRoutedTransfers")]
    pub has_routed_transfers: bool,
    /// true if street routing is available
    #[serde(rename = "hasStreetRouting")]
    pub has_street_routing: bool,
    /// limit for the number of `many` locations for one-to-many requests 
    #[serde(rename = "maxOneToManySize")]
    pub max_one_to_many_size: f64,
    /// limit for maxTravelTime API param in minutes
    #[serde(rename = "maxOneToAllTravelTimeLimit")]
    pub max_one_to_all_travel_time_limit: f64,
    /// limit for maxPrePostTransitTime API param in seconds
    #[serde(rename = "maxPrePostTransitTimeLimit")]
    pub max_pre_post_transit_time_limit: f64,
    /// limit for maxDirectTime API param in seconds
    #[serde(rename = "maxDirectTimeLimit")]
    pub max_direct_time_limit: f64,
    /// true if experimental route shapes debug download API is enabled
    #[serde(rename = "shapesDebugEnabled")]
    pub shapes_debug_enabled: bool,
}

impl ServerConfig {
    pub fn new(motis_version: String, has_elevation: bool, has_routed_transfers: bool, has_street_routing: bool, max_one_to_many_size: f64, max_one_to_all_travel_time_limit: f64, max_pre_post_transit_time_limit: f64, max_direct_time_limit: f64, shapes_debug_enabled: bool) -> ServerConfig {
        ServerConfig {
            motis_version,
            has_elevation,
            has_routed_transfers,
            has_street_routing,
            max_one_to_many_size,
            max_one_to_all_travel_time_limit,
            max_pre_post_transit_time_limit,
            max_direct_time_limit,
            shapes_debug_enabled,
        }
    }
}

