CREATE TABLE IF NOT EXISTS care.clients (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    postcode_id VARCHAR(255) NOT NULL,
    roundsys_pk VARCHAR(255) NULL UNIQUE
);
