CREATE TABLE IF NOT EXISTS care.weekly_hours (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NULL,
    monday_morning BOOLEAN NOT NULL,
    monday_lunch BOOLEAN NOT NULL,
    monday_tea BOOLEAN NOT NULL,
    monday_evening BOOLEAN NOT NULL,
    monday_night BOOLEAN NOT NULL,
    tuesday_morning BOOLEAN NOT NULL,
    tuesday_lunch BOOLEAN NOT NULL,
    tuesday_tea BOOLEAN NOT NULL,
    tuesday_evening BOOLEAN NOT NULL,
    tuesday_night BOOLEAN NOT NULL,
    wednesday_morning BOOLEAN NOT NULL,
    wednesday_lunch BOOLEAN NOT NULL,
    wednesday_tea BOOLEAN NOT NULL,
    wednesday_evening BOOLEAN NOT NULL,
    wednesday_night BOOLEAN NOT NULL,
    thursday_morning BOOLEAN NOT NULL,
    thursday_lunch BOOLEAN NOT NULL,
    thursday_tea BOOLEAN NOT NULL,
    thursday_evening BOOLEAN NOT NULL,
    thursday_night BOOLEAN NOT NULL,
    friday_morning BOOLEAN NOT NULL,
    friday_lunch BOOLEAN NOT NULL,
    friday_tea BOOLEAN NOT NULL,
    friday_evening BOOLEAN NOT NULL,
    friday_night BOOLEAN NOT NULL,
    saturday_morning BOOLEAN NOT NULL,
    saturday_lunch BOOLEAN NOT NULL,
    saturday_tea BOOLEAN NOT NULL,
    saturday_evening BOOLEAN NOT NULL,
    saturday_night BOOLEAN NOT NULL,
    sunday_morning BOOLEAN NOT NULL,
    sunday_lunch BOOLEAN NOT NULL,
    sunday_tea BOOLEAN NOT NULL,
    sunday_evening BOOLEAN NOT NULL,
    sunday_night BOOLEAN NOT NULL,
    note VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES care.users (id)
);
