/*
 * MOTIS API
 *
 * This is the MOTIS routing API.  Overview of MOTIS API versions:  MOTIS 0.x - deprecated/discontinued  MOTIS 2.x - current, providing:  * /api/v6/{plan,trip,stoptimes,one-to-all,map/stops,map/trips} no longer set optional level to 0; since MOTIS 2.9.x * /api/v5/{plan,trip,stoptimes,map/trips} renamed METRO mode to SUBURBAN, AREAL_LIFT to AERIAL_LIFT; since MOTIS 2.5.0 * /api/v4/{plan,trip,stoptimes,map/trips} new displayName property, routeShortName only contains actual route short name from source; since MOTIS 2.2.0 * /api/v3/plan with correct maxTransfers API parameter (transfers actually corresponding to number of changes between transit legs (and not to number of transit legs), i.e. maxTransfers=0 returns direct public transit connections, as expected); since MOTIS 2.0.84  * /api/v2/{plan,trip} returns Google polylines with precision=6; since MOTIS 2.0.60 * /api/v1/{plan,trip} returns Google polylines with precision=7 (not defined for |longitude|>107) * /api/v1/_* all other endpoints  If you use the JS client lib https://www.npmjs.com/package/@motis-project/motis-client, endpoint versions will be taken into account automatically (i.e. the newest one available will be used). 
 *
 * The version of the OpenAPI document: v6
 * Contact: felix@triptix.tech
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`refresh_itinerary`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefreshItineraryError {
    Status400(models::Error),
    Status500(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`refresh_itinerary_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RefreshItineraryPostError {
    Status400(models::Error),
    Status500(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`stop_info`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StopInfoError {
    Status422(models::Error),
    Status500(models::Error),
    Status400(models::Error),
    Status404(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`stoptimes`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StoptimesError {
    Status422(models::Error),
    Status404(models::Error),
    Status500(models::Error),
    Status400(models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`trip`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TripError {
    Status422(models::Error),
    Status400(models::Error),
    Status404(models::Error),
    Status500(models::Error),
    UnknownValue(serde_json::Value),
}


/// Experimental (API might change without prior notice and without API version bump). Only supports walking at start/end or station-to-station itineraries.  All parameters mirror those of the `plan` endpoint - see the `plan` endpoint for their descriptions. 
pub async fn refresh_itinerary(configuration: &configuration::Configuration, itinerary_id: &str, require_display_name_match: Option<bool>, join_interlined_legs: Option<bool>, detailed_transfers: Option<bool>, detailed_legs: Option<bool>, with_fares: Option<bool>, with_scheduled_skipped_stops: Option<bool>, num_leg_alternatives: Option<i32>, transit_modes: Option<Vec<models::Mode>>, pre_transit_modes: Option<Vec<models::Mode>>, post_transit_modes: Option<Vec<models::Mode>>, pedestrian_profile: Option<models::PedestrianProfile>, use_routed_transfers: Option<bool>, require_bike_transport: Option<bool>, require_car_transport: Option<bool>, no_compulsory_reservation: Option<bool>, language: Option<Vec<String>>, pedestrian_speed: Option<f64>, cycling_speed: Option<f64>, elevation_costs: Option<models::ElevationCosts>, max_matching_distance: Option<f64>, max_pre_transit_time: Option<i32>, max_post_transit_time: Option<i32>, pre_transit_rental_form_factors: Option<Vec<models::RentalFormFactor>>, post_transit_rental_form_factors: Option<Vec<models::RentalFormFactor>>, pre_transit_rental_propulsion_types: Option<Vec<models::RentalPropulsionType>>, post_transit_rental_propulsion_types: Option<Vec<models::RentalPropulsionType>>, pre_transit_rental_providers: Option<Vec<String>>, post_transit_rental_providers: Option<Vec<String>>, pre_transit_rental_provider_groups: Option<Vec<String>>, post_transit_rental_provider_groups: Option<Vec<String>>, ignore_pre_transit_rental_return_constraints: Option<bool>, ignore_post_transit_rental_return_constraints: Option<bool>) -> Result<models::Itinerary, Error<RefreshItineraryError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_itinerary_id = itinerary_id;
    let p_query_require_display_name_match = require_display_name_match;
    let p_query_join_interlined_legs = join_interlined_legs;
    let p_query_detailed_transfers = detailed_transfers;
    let p_query_detailed_legs = detailed_legs;
    let p_query_with_fares = with_fares;
    let p_query_with_scheduled_skipped_stops = with_scheduled_skipped_stops;
    let p_query_num_leg_alternatives = num_leg_alternatives;
    let p_query_transit_modes = transit_modes;
    let p_query_pre_transit_modes = pre_transit_modes;
    let p_query_post_transit_modes = post_transit_modes;
    let p_query_pedestrian_profile = pedestrian_profile;
    let p_query_use_routed_transfers = use_routed_transfers;
    let p_query_require_bike_transport = require_bike_transport;
    let p_query_require_car_transport = require_car_transport;
    let p_query_no_compulsory_reservation = no_compulsory_reservation;
    let p_query_language = language;
    let p_query_pedestrian_speed = pedestrian_speed;
    let p_query_cycling_speed = cycling_speed;
    let p_query_elevation_costs = elevation_costs;
    let p_query_max_matching_distance = max_matching_distance;
    let p_query_max_pre_transit_time = max_pre_transit_time;
    let p_query_max_post_transit_time = max_post_transit_time;
    let p_query_pre_transit_rental_form_factors = pre_transit_rental_form_factors;
    let p_query_post_transit_rental_form_factors = post_transit_rental_form_factors;
    let p_query_pre_transit_rental_propulsion_types = pre_transit_rental_propulsion_types;
    let p_query_post_transit_rental_propulsion_types = post_transit_rental_propulsion_types;
    let p_query_pre_transit_rental_providers = pre_transit_rental_providers;
    let p_query_post_transit_rental_providers = post_transit_rental_providers;
    let p_query_pre_transit_rental_provider_groups = pre_transit_rental_provider_groups;
    let p_query_post_transit_rental_provider_groups = post_transit_rental_provider_groups;
    let p_query_ignore_pre_transit_rental_return_constraints = ignore_pre_transit_rental_return_constraints;
    let p_query_ignore_post_transit_rental_return_constraints = ignore_post_transit_rental_return_constraints;

    let uri_str = format!("{}/api/v6/refresh-itinerary", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("itineraryId", &p_query_itinerary_id.to_string())]);
    if let Some(ref param_value) = p_query_require_display_name_match {
        req_builder = req_builder.query(&[("requireDisplayNameMatch", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_join_interlined_legs {
        req_builder = req_builder.query(&[("joinInterlinedLegs", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_detailed_transfers {
        req_builder = req_builder.query(&[("detailedTransfers", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_detailed_legs {
        req_builder = req_builder.query(&[("detailedLegs", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_fares {
        req_builder = req_builder.query(&[("withFares", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_scheduled_skipped_stops {
        req_builder = req_builder.query(&[("withScheduledSkippedStops", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_num_leg_alternatives {
        req_builder = req_builder.query(&[("numLegAlternatives", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_transit_modes {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("transitModes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("transitModes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_pre_transit_modes {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("preTransitModes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("preTransitModes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_post_transit_modes {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("postTransitModes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("postTransitModes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_pedestrian_profile {
        req_builder = req_builder.query(&[("pedestrianProfile", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_use_routed_transfers {
        req_builder = req_builder.query(&[("useRoutedTransfers", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_require_bike_transport {
        req_builder = req_builder.query(&[("requireBikeTransport", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_require_car_transport {
        req_builder = req_builder.query(&[("requireCarTransport", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_no_compulsory_reservation {
        req_builder = req_builder.query(&[("noCompulsoryReservation", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("language".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("language", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_pedestrian_speed {
        req_builder = req_builder.query(&[("pedestrianSpeed", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_cycling_speed {
        req_builder = req_builder.query(&[("cyclingSpeed", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_elevation_costs {
        req_builder = req_builder.query(&[("elevationCosts", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_matching_distance {
        req_builder = req_builder.query(&[("maxMatchingDistance", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_pre_transit_time {
        req_builder = req_builder.query(&[("maxPreTransitTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_max_post_transit_time {
        req_builder = req_builder.query(&[("maxPostTransitTime", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_pre_transit_rental_form_factors {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("preTransitRentalFormFactors".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("preTransitRentalFormFactors", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_post_transit_rental_form_factors {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("postTransitRentalFormFactors".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("postTransitRentalFormFactors", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_pre_transit_rental_propulsion_types {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("preTransitRentalPropulsionTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("preTransitRentalPropulsionTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_post_transit_rental_propulsion_types {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("postTransitRentalPropulsionTypes".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("postTransitRentalPropulsionTypes", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_pre_transit_rental_providers {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("preTransitRentalProviders".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("preTransitRentalProviders", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_post_transit_rental_providers {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("postTransitRentalProviders".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("postTransitRentalProviders", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_pre_transit_rental_provider_groups {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("preTransitRentalProviderGroups".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("preTransitRentalProviderGroups", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_post_transit_rental_provider_groups {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("postTransitRentalProviderGroups".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("postTransitRentalProviderGroups", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_ignore_pre_transit_rental_return_constraints {
        req_builder = req_builder.query(&[("ignorePreTransitRentalReturnConstraints", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_ignore_post_transit_rental_return_constraints {
        req_builder = req_builder.query(&[("ignorePostTransitRentalReturnConstraints", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Itinerary`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Itinerary`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RefreshItineraryError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Experimental (API might change without prior notice and without API version bump). Only supports walking at start/end or station-to-station itineraries.  All `RefreshItineraryPostBody` fields mirror the parameters of the `plan` endpoint - see the `plan` endpoint for their descriptions. 
pub async fn refresh_itinerary_post(configuration: &configuration::Configuration, refresh_itinerary_post_body: models::RefreshItineraryPostBody) -> Result<models::Itinerary, Error<RefreshItineraryPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_refresh_itinerary_post_body = refresh_itinerary_post_body;

    let uri_str = format!("{}/api/v6/refresh-itinerary", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_refresh_itinerary_post_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Itinerary`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Itinerary`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RefreshItineraryPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn stop_info(configuration: &configuration::Configuration, stop_id: Option<&str>, center: Option<&str>, radius: Option<i32>, exact_radius: Option<bool>, language: Option<Vec<String>>) -> Result<models::StopInfo200Response, Error<StopInfoError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_stop_id = stop_id;
    let p_query_center = center;
    let p_query_radius = radius;
    let p_query_exact_radius = exact_radius;
    let p_query_language = language;

    let uri_str = format!("{}/api/v6/stop", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_stop_id {
        req_builder = req_builder.query(&[("stopId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_center {
        req_builder = req_builder.query(&[("center", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_radius {
        req_builder = req_builder.query(&[("radius", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exact_radius {
        req_builder = req_builder.query(&[("exactRadius", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("language".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("language", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::StopInfo200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::StopInfo200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StopInfoError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn stoptimes(configuration: &configuration::Configuration, stop_id: Option<&str>, center: Option<&str>, time: Option<chrono::DateTime<chrono::FixedOffset>>, arrive_by: Option<bool>, both: Option<bool>, direction: Option<&str>, window: Option<i32>, mode: Option<Vec<models::Mode>>, n: Option<i32>, radius: Option<i32>, exact_radius: Option<bool>, fetch_stops: Option<bool>, page_cursor: Option<&str>, with_scheduled_skipped_stops: Option<bool>, realtime_mode: Option<models::RealtimeMode>, language: Option<Vec<String>>, with_alerts: Option<bool>) -> Result<models::Stoptimes200Response, Error<StoptimesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_stop_id = stop_id;
    let p_query_center = center;
    let p_query_time = time;
    let p_query_arrive_by = arrive_by;
    let p_query_both = both;
    let p_query_direction = direction;
    let p_query_window = window;
    let p_query_mode = mode;
    let p_query_n = n;
    let p_query_radius = radius;
    let p_query_exact_radius = exact_radius;
    let p_query_fetch_stops = fetch_stops;
    let p_query_page_cursor = page_cursor;
    let p_query_with_scheduled_skipped_stops = with_scheduled_skipped_stops;
    let p_query_realtime_mode = realtime_mode;
    let p_query_language = language;
    let p_query_with_alerts = with_alerts;

    let uri_str = format!("{}/api/v6/stoptimes", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_stop_id {
        req_builder = req_builder.query(&[("stopId", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_center {
        req_builder = req_builder.query(&[("center", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_time {
        req_builder = req_builder.query(&[("time", &param_value.to_rfc3339())]);
    }
    if let Some(ref param_value) = p_query_arrive_by {
        req_builder = req_builder.query(&[("arriveBy", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_both {
        req_builder = req_builder.query(&[("both", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_direction {
        req_builder = req_builder.query(&[("direction", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_window {
        req_builder = req_builder.query(&[("window", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_mode {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("mode".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("mode", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_n {
        req_builder = req_builder.query(&[("n", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_radius {
        req_builder = req_builder.query(&[("radius", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_exact_radius {
        req_builder = req_builder.query(&[("exactRadius", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_fetch_stops {
        req_builder = req_builder.query(&[("fetchStops", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_page_cursor {
        req_builder = req_builder.query(&[("pageCursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_with_scheduled_skipped_stops {
        req_builder = req_builder.query(&[("withScheduledSkippedStops", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_realtime_mode {
        req_builder = req_builder.query(&[("realtimeMode", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("language".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("language", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref param_value) = p_query_with_alerts {
        req_builder = req_builder.query(&[("withAlerts", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Stoptimes200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Stoptimes200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<StoptimesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn trip(configuration: &configuration::Configuration, trip_id: &str, with_scheduled_skipped_stops: Option<bool>, detailed_legs: Option<bool>, join_interlined_legs: Option<bool>, language: Option<Vec<String>>) -> Result<models::Itinerary, Error<TripError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_trip_id = trip_id;
    let p_query_with_scheduled_skipped_stops = with_scheduled_skipped_stops;
    let p_query_detailed_legs = detailed_legs;
    let p_query_join_interlined_legs = join_interlined_legs;
    let p_query_language = language;

    let uri_str = format!("{}/api/v6/trip", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("tripId", &p_query_trip_id.to_string())]);
    if let Some(ref param_value) = p_query_with_scheduled_skipped_stops {
        req_builder = req_builder.query(&[("withScheduledSkippedStops", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_detailed_legs {
        req_builder = req_builder.query(&[("detailedLegs", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_join_interlined_legs {
        req_builder = req_builder.query(&[("joinInterlinedLegs", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_language {
        req_builder = match "csv" {
            "multi" => req_builder.query(&param_value.into_iter().map(|p| ("language".to_owned(), p.to_string())).collect::<Vec<(std::string::String, std::string::String)>>()),
            _ => req_builder.query(&[("language", &param_value.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]),
        };
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Itinerary`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Itinerary`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TripError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

